export const SET_USER_DETAILS = 'SET_USER_DETAILS'
export const SET_DEVICE_CODE = 'SET_DEVICE_CODE'
export const SET_FRANCHIES_CODE = 'SET_FRANCHIES_CODE'
export const SET_LAST_ORDER_NO = 'SET_LAST_ORDER_NO'
