export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_DEVICE_CODE = "SET_DEVICE_CODE";
export const SET_FRANCHISE_CODE = "SET_FRANCHISE_CODE";
export const SET_LAST_ORDER_NO = "SET_LAST_ORDER_NO";
export const SET_TOKEN = "SET_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
