export const SET_KITCHENS_ITEMS = 'SET_KITCHENS_ITEMS'
export const SET_PRINTING_SERVERS = 'SET_PRINTING_SERVERS'
export const CREATED_DATE = 'CREATED_DATE'
export const CREATED_TIME = 'CREATED_TIME'
