export const WAITER = 'waiter'
export const CARHOP = 'carhop'
export const SWITCH_WAITER = 'can_switch_between_waiter'
export const SWITCH_WAITER_API = 'reservations.o.switch_waiter'
export const BRAND_SETTINGS = 'brands.brand_settings'
export const REPRINT_ORDER = 'orders.o.reprint_order'
export const MODIFY_ORDER = 'orders.o.modify_order'
export const CANCEL_ORDER = 'orders.o.cancel_order'

export const CHANGE_AVATAR = 'store_users.o.change_avatar.store'
export const CHANGE_PASSWORD = 'store_users.o.change_pass_action.store'
export const CHANGE_NAME_EMAIL = 'store_users.o.change_name_email_action.store'
export const SEE_OTHERS_ORDERS = 'can_see_others_orders'

export const TOKEN_NUMBER = 'stores.o.store_token_screen_form_action_id'
export const PRINT_BUSINESS_SUMMARY = 'orders.dashboard_business_summary'
export const CARHOP_COMPLETED_ORDERS = 'orders.carhop_completed_orders.api'
