export const CUSTOMER_LIST = "CUSTOMER_LIST";
export const SELECTED_CUSTOMER = "SELECTED_CUSTOMER";
export const SELECTED_CUSTOMER_ADDRESSES = "SELECTED_CUSTOMER_ADDRESSES";
export const SELECTED_CUSTOMER_ADDRESS = "SELECTED_CUSTOMER_ADDRESS";
