export const BUSINESS_SUMMERY = 'BUSINESS_SUMMERY'
export const DATE_FROM = 'DATE_FROM'
export const DATE_TO = 'DATE_TO'
export const HOUR_FROM = 'HOUR_FROM'
export const HOUR_TO = 'HOUR_TO'
export const TIME_MODE = 'TIME_MODE'
export const SUPERVISOR_PASSWORD = 'SUPERVISOR_PASSWORD'
