export const SET_ITEM = 'SET_ITEM'
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM'
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM'
export const INCREMENT_ORDER_ITEM_QUANTITY = 'INCREMENT_ORDER_ITEM_QUANTITY'
