export const SET_ITEM = "SET_ITEM";
export const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
export const ADD_ORDER_ITEM_MODIFIER = "ADD_ORDER_ITEM_MODIFIER";
export const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";
export const INCREMENT_ORDER_ITEM_QUANTITY = "INCREMENT_ORDER_ITEM_QUANTITY";
export const UPDATE_MODIFER_ORDER_ITEM = "UPDATE_MODIFER_ORDER_ITEM";
export const SET_ITEM_TAX = "SET_ITEM_TAX";
