export const SET_CURRENCY = "SET_CURRENCY";
export const SET_LOCATION = "SET_LOCATION";
export const SET_LOCALE = "SET_LOCALE";
export const SET_REFERRALS = "SET_REFERRALS";
export const SET_TIMEZONE = "SET_TIMEZONE";
export const SET_AVAILABLE_LANGUAGES = "SET_AVAILABLE_LANGUAGES";
export const SET_LANGUAGE_DIRECTION = "SET_LANGUAGE_DIRECTION";
export const SET_TRASLATIONS = "SET_TRASLATIONS";
export const SET_STORE = "SET_STORE";
export const SET_BRAND = "SET_BRAND";
export const USER_DETAILS = "USER_DETAILS";
export const RESET = "RESET";

export const SET_MODAL = "SET_MODAL";
