/* CATEGORY SECTION */
export const REFERENCE_FIELD_SUBCATEGORY_TO_CATEGORY = 'category'
export const REFERENCE_FIELD_CATEGORY_TO_SUBCATEGORY = '_id'

export const REFERENCE_FIELD_ITEM_TO_CATEGORY = 'category'
export const REFERENCE_FIELD_CATEGORY_TO_ITEM = '_id'

export const REFERENCE_FIELD_ITEM_TO_SUBCATEGORY = 'sub_category'
export const REFERENCE_FIELD_SUBCATEGORY_TO_ITEM = '_id'

/* MODIFIERS SECTION */

export const REFERENCE_FIELD_ITEM_TO_MODIFIER_GROUP = '_id'
export const REFERENCE_FIELD_MODIFIER_GROUP_TO_SUBGROUP = '_id'
export const REFERENCE_FIELD_MODIFIER_GROUP_TO_MODIFIER = '_id'
export const REFERENCE_FIELD_MODIFIER_SUBGROUP_TO_MODIDIER =
  'modifier_sub_group'
export const FIELD_MODIFIER_NAME = '_id'
